config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions', 
    registrations: 'users/registrations'}

  root to: 'pages#home'
  resources :movies, only: [:index, :show]
  resources :events, only: [:create, :index]
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  belongs_to :user
  has_many :events
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :calendar
  has_one :event_movie
  has_one :movie, through: :event_movie
end

app/models/event_movie.rb
class EventMovie < ApplicationRecord
  belongs_to :event
  belongs_to :movie
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :genre_movies
  has_many :movies, through: :genre_movies
end

app/models/genre_movie.rb
class GenreMovie < ApplicationRecord
  belongs_to :genre
  belongs_to :movie
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :genre_movies
  has_many :genres, through: :genre_movies
  has_many :events, through: :event_movies

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :calendar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.where(calendar: current_user.calendar)
    @events_dates = @events.map(&:release_date).uniq.sort
  end

  def create
    @calendar = current_user.calendar
    @movie = Movie.find(params[:movie_id])
    @event = Event.new(calendar: @calendar, release_date: @movie.release_date)
    @event.save!
    EventMovie.create!(movie: @movie, event: @event)
    redirect_to events_path
  end

  private

  def event_params
    params.require(:event).permit(:release_date)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all.order(:release_date)
    @events = Event.where(calendar: current_user.calendar)
    @events_movies = @events.map(&:movie)
  end

  def show
    @movie = Movie.find(params[:id])
    @genres = @movie.genres.map(&:name)
    @events = Event.where(calendar: current_user.calendar)
    @events_movies = @events.map(&:movie)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/events/index.html.erb
<div class="container">
  <h1>My events</h1>
  <h4>My movies releases</h4>
  <br>
  <div class="movies-releases">
    <% @events_dates.each do |date| %>
      <% events = @events.where(release_date: date) %>
      <p class="event-date"><%= date %></p>
      <div class="d-flex pb-5">
        <% events.each do |event| %>
          <div class="cards d-flex pe-2">
            <%= image_tag event.movie.poster_path, class:'card-category' %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WishesCalendar</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://kit.fontawesome.com/1db11ea788.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/movies/index.html.erb
<div class="container" data-controller="popover">
  <div class="cards">
    <% @movies.each do |movie| %>
      <div class="card">
        <%= link_to movie_path(movie) do %>
          <%= image_tag movie.poster_path, class: 'card-category' %>
        <% end %>
        <div class="movie-title text-center">
          <div class="info-movie">
            <p><%= movie.title %></p>
            <p><%= movie.release_date %></p>
          </div>
          
            <%= form_with url: "/events", method: :post, class: 'form-movie' do |f| %>
              <%= f.hidden_field :movie_id, value: movie.id %>
              <% if @events_movies.include?(movie) %>
                <span class="d-inline-block" tabindex="0" data-bs-toggle="popover" data-bs-trigger="hover focus" data-bs-content="Already in your Calendar">
                  <%= f.button '<i class="fa-solid fa-plus disabled"></i>'.html_safe, class: "button my-button", disabled: true %>
                </span>
              <% else %>
                <span class="d-inline-block" tabindex="0" data-bs-toggle="popover" data-bs-trigger="hover focus" data-bs-content="Add to Calendar">
                  <%= f.button '<i class="fa-solid fa-plus"></i>'.html_safe, class: "button my-button" %>
                </span>
              <% end %>
            <% end %>
        </div> 

      </div>
    <% end %>
  </div>
</div>

app/views/movies/show.html.erb
<div class="banner">
  <div class="banner-container  d-flex  ">
    <%= image_tag @movie.poster_path, class:'poster-movie' %>

    <div class="description-movie">
      <h2><span class="title-movie"><%= @movie.title %></span><span class="year-movie"> (<%= @movie.release_date.year %>)</span></h2>
      <p><%= @movie.release_date %></p>
      <h4>Synopsis</h4>
      <p><%= @movie.synopsis %></p>
      <h4>Director</h4>
      <p><%= @movie.director %></p>
      <h4>Genre(s)</h4>
      <p><%= "#{@genres.join(", ")}" %></p>
      <% if @events_movies.include?(@movie) %>
        <button class="btn btn-danger disabled" id="btn-disabled">Already in your calendar</button>
      <% else %>
        <%= form_with url: "/events", method: :post do |f| %>
          <%= f.hidden_field :movie_id, value: @movie.id %>
          <%= f.submit "Add to my Calendar", class:'btn btn-danger' %>
        <% end %>
      <% end %>
    </div>        
  </div>
 
</div>

app/views/pages/home.html.erb
<button type="button" 
        class="btn btn-lg btn-danger" 
        data-bs-toggle="popover" 
        title="Popover title" 
        data-bs-content="Amazing content, right ?">
        Click to toggle popover
</button>  

<p class="test">test</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Movies", movies_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Events", events_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Events", events_path, class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>